# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table ingredient (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  amount                        double,
  measure                       varchar(255),
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_ingredient primary key (id)
);

create table recipe (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  stars                         integer,
  description                   varchar(255),
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_recipe primary key (id)
);

create table recipe_ingredient (
  recipe_id                     bigint not null,
  ingredient_id                 bigint not null,
  constraint pk_recipe_ingredient primary key (recipe_id,ingredient_id)
);

-- foreign keys and indices
create index ix_recipe_ingredient_recipe on recipe_ingredient (recipe_id);
alter table recipe_ingredient add constraint fk_recipe_ingredient_recipe foreign key (recipe_id) references recipe (id) on delete restrict on update restrict;

create index ix_recipe_ingredient_ingredient on recipe_ingredient (ingredient_id);
alter table recipe_ingredient add constraint fk_recipe_ingredient_ingredient foreign key (ingredient_id) references ingredient (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table recipe_ingredient drop constraint if exists fk_recipe_ingredient_recipe;
drop index if exists ix_recipe_ingredient_recipe;

alter table recipe_ingredient drop constraint if exists fk_recipe_ingredient_ingredient;
drop index if exists ix_recipe_ingredient_ingredient;

-- drop all
drop table if exists ingredient;

drop table if exists recipe;

drop table if exists recipe_ingredient;

