# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table ingredients (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  amount                        double,
  measure                       varchar(255),
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_ingredients primary key (id)
);

create table recipe (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  stars                         integer,
  description                   varchar(255),
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_recipe primary key (id)
);

create table recipe_ingredients (
  recipe_id                     bigint not null,
  ingredients_id                bigint not null,
  constraint pk_recipe_ingredients primary key (recipe_id,ingredients_id)
);

-- foreign keys and indices
create index ix_recipe_ingredients_recipe on recipe_ingredients (recipe_id);
alter table recipe_ingredients add constraint fk_recipe_ingredients_recipe foreign key (recipe_id) references recipe (id) on delete restrict on update restrict;

create index ix_recipe_ingredients_ingredients on recipe_ingredients (ingredients_id);
alter table recipe_ingredients add constraint fk_recipe_ingredients_ingredients foreign key (ingredients_id) references ingredients (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table recipe_ingredients drop constraint if exists fk_recipe_ingredients_recipe;
drop index if exists ix_recipe_ingredients_recipe;

alter table recipe_ingredients drop constraint if exists fk_recipe_ingredients_ingredients;
drop index if exists ix_recipe_ingredients_ingredients;

-- drop all
drop table if exists ingredients;

drop table if exists recipe;

drop table if exists recipe_ingredients;

